### ISSUE TITLE
urrently configured default filesystem: LocalFileSystem. fs.defaultFS (file:///) is not supported

### ISSUE THREAD

**Issue by caizx666** [parrot-stream/docker-impala-kudu#1]
E0913 13:26:25.406966  3021 impala-server.cc:249] Currently configured default filesystem: LocalFileSystem. fs.defaultFS (file:///) is not supported.ERROR: block location tracking is not properly enabled because
  - dfs.datanode.hdfs-blocks-metadata.enabled is not enabled.
  - dfs.client.file-block-storage-locations.timeout.millis is too low. It should be at least 10 seconds.

Before installing Impala_Kudu, you must have already installed and configured services for HDFS (though it is not used by Kudu), the Hive Metastore (where Impala stores its metadata), and Kudu.

**Comment by mcapitanio** [comment]
Solved with the latest image!
