### ISSUE TITLE
The last version of impala is 2.7.0

### ISSUE THREAD

**Issue by zhimiQi** [parrot-stream/docker-impala-kudu#5]
I pull the last version of impala-kudu, It,s show me:

> Shell version: Impala Shell v2.7.0-IMPALA_KUDU-cdh5 (10d4ebe) built on Mon Nov 21 23:11:10 PST 2016
Server version: impalad version 2.7.0-IMPALA_KUDU-cdh5 RELEASE (build 10d4ebec3c23961218e972e74e9d342ffc417af1)

How to update to Impala Kudu 2.9.0,?

**Comment by mcapitanio** [comment]
Hi @zhimiQi , if you can use the repo:

[Impala](https://github.com/parrot-stream/docker-impala)

where you can find the 2.12 version and also the 3.0.0 version of Impala.
Then you can tell to Impala to use Kudu as storage instead of HDFS in a 'create' or 'alter' table command, as follows:

TBLPROPERTIES('kudu.master_addresses'='kudu_master:7051') 

I've never used in this way but it should work as stated here:

https://www.cloudera.com/documentation/enterprise/latest/topics/impala_kudu.html

Let me know if it works!

**Comment by zhimiQi** [comment]
Hi @mcapitanio ,

Thanks for you help!

I used Impala of the last version, I find this version show me:

> Welcome to the Impala shell.
(Impala Shell v2.12.0-cdh5.15.1 (64f4e19) built on Thu Aug  9 09:21:02 PDT 2018)
You can run a single query from the command line using the '-q' option.

So I pull this [Impala ](https://github.com/parrot-stream/docker-impala/tree/3.0.0-cdh6.0.0) .

I start with Docker Compose 

> docker-compose -p parrot

It's show me the following:

> HIVE not ready! Exiting...

 I'm trying to fix this. The Hive docker show me:

> Starting NameNode...
hdfs-namenode: ERROR (no such process)
Starting DataNode...
hdfs-datanode: ERROR (no such process)

So, I think hive docker of [parrotstream/hive:3.1.0](https://github.com/parrot-stream/docker-hive/tree/3.1.0) has some error.
Can you help me fix this error?
Thank you again.

**Comment by mcapitanio** [comment]
@zhimiQi , have you started Zookeepr and Hadoop before starting Hive?

For Hive please use this branch:

https://github.com/parrot-stream/docker-hive/tree/1.1.0-cdh5.11.1

**Comment by zhimiQi** [comment]
Hi @mcapitanio , 
I think I found the errors of parrotstream/hive:3.1.0.
In the [Dockerfile](https://github.com/parrot-stream/docker-hive/blob/3.1.0/Dockerfile), 
`ENV HADOOP_HOME /opt/hadoop
ENV HADOOP_CONF_DIR /opt/hadoop/etc/hadoop`
The above code should be modified:
`ENV HADOOP_HOME /usr/lib/hadoop
ENV HADOOP_CONF_DIR /usr/lib/hadoop/etc/hadoop`
If hive docker has errors, 
`$HIVE_HOME/bin/schematool -dbType postgres -initSchema`
following this error
> ERROR:  relation "BUCKETING_COLS" already exists

I should clean data of postgres.

**Comment by mcapitanio** [comment]
Hi @zhimiQi , great! I had no chance to deeply test the latest version of Hive: when I have just a bit of time I'll check it again...

**Comment by zhimiQi** [comment]
@mcapitanio , 
I used Hive of branch:
https://github.com/parrot-stream/docker-hive/tree/1.1.0-cdh5.11.1
It's works! Thanks for you help!
I thinks you should modify [docker-compose.yml](https://github.com/parrot-stream/docker-impala/blob/latest/docker-compose.yml)
`image: parrotstream/hive:3.1.0`
To
`image: parrotstream/hive:1.1.0-cdh5.11.1`
Thanks for you help again!

**Comment by mcapitanio** [comment]
@zhimiQi . thanks a lot, I'll check that asap!!
